{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-4.2.0.jar",
          "url": "databinding-compiler-4.2.0.jar",
          "size": 1175252,
          "sha512": "e5f4c57f5353cd7c6365cfb751b67d7ede9877e99ca72592dafb4c3985259db586e1a97aaf7ca60c78197e19276a639e0682e2b34b9cd270f3d9f5f55c2d53d1",
          "sha256": "cd03b23e2869179092b084d699bc860d8f052ae7e6fbcef07d676c5541136c8e",
          "sha1": "4c3df23d728bcaba481124e12751354080576066",
          "md5": "734f32509711364f23af6cf4f4fd0f0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-4.2.0.jar",
          "url": "databinding-compiler-4.2.0.jar",
          "size": 1175252,
          "sha512": "e5f4c57f5353cd7c6365cfb751b67d7ede9877e99ca72592dafb4c3985259db586e1a97aaf7ca60c78197e19276a639e0682e2b34b9cd270f3d9f5f55c2d53d1",
          "sha256": "cd03b23e2869179092b084d699bc860d8f052ae7e6fbcef07d676c5541136c8e",
          "sha1": "4c3df23d728bcaba481124e12751354080576066",
          "md5": "734f32509711364f23af6cf4f4fd0f0b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-4.2.0-javadoc.jar",
          "url": "databinding-compiler-4.2.0-javadoc.jar",
          "size": 351897,
          "sha512": "91c2d523054087ca8e82eb27a983548657a74b582c3b69cd210ad9332d970f1eaafc127de4756f272eaceef811aa2e351d286e7267d2c8c399b8b4054266cc1e",
          "sha256": "9dac3f18435425ef02c7ff8adbd43360cb9c4e71d6ee2e44eafed27d03976f58",
          "sha1": "1db1223ed9367d22a063955fb76ffd83de3ad489",
          "md5": "ef60beb33f4e1fec23fe3e6071f139e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-4.2.0-sources.jar",
          "url": "databinding-compiler-4.2.0-sources.jar",
          "size": 564713,
          "sha512": "88f0b5f13d71aee9d87da614dd73caed7fd097a42da169d4cd605ee8b61fe1a557935658f8ed696d49be31dc94c488d6d4d1a1125b8bbf9d1ea9ce3710b75d9f",
          "sha256": "30f73c2792b3d04b90b4ef263c059c7ffb74c1768a9e8471369ee8690b18dcb3",
          "sha1": "a46578c8e61a76861af220cfe1c12a620e99e225",
          "md5": "999b6f5edb32f4a0d00eb7f35bc694f2"
        }
      ]
    }
  ]
}
