{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-model",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lint-model-27.2.0.jar",
          "url": "lint-model-27.2.0.jar",
          "size": 179795,
          "sha512": "1c53d0a239a6927c214be2d86d7ab743166c7d61e8619d31ffa2bdebc9afe49a99ee7821a4e5d68a0c3fea8064138240e52c742c02358e76e88f54bfedbda0f9",
          "sha256": "cf1fefdc98e7091c206e984c3828d80ab1c4c51d179c6b4f699d6e3c5929912f",
          "sha1": "997bf8f85c6b6a2ca99013a7a4deb5d68fe26a06",
          "md5": "5eb70534c969ef1d8e54b9a156dd851a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lint-model-27.2.0.jar",
          "url": "lint-model-27.2.0.jar",
          "size": 179795,
          "sha512": "1c53d0a239a6927c214be2d86d7ab743166c7d61e8619d31ffa2bdebc9afe49a99ee7821a4e5d68a0c3fea8064138240e52c742c02358e76e88f54bfedbda0f9",
          "sha256": "cf1fefdc98e7091c206e984c3828d80ab1c4c51d179c6b4f699d6e3c5929912f",
          "sha1": "997bf8f85c6b6a2ca99013a7a4deb5d68fe26a06",
          "md5": "5eb70534c969ef1d8e54b9a156dd851a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-model-27.2.0-javadoc.jar",
          "url": "lint-model-27.2.0-javadoc.jar",
          "size": 261,
          "sha512": "c6fd1ffd196b670ce6af231c1c24ad5c49a7b313b507c5ccec03d20b03b0c417a7d950b99a3845e66c51b714e0b3fef3a7b03f41615b1624f5d5b5208c642dab",
          "sha256": "ec0e3c6efd107529786e1ae6480e266285dd0fd4c5e9344f2dc1b3a97ca38950",
          "sha1": "cc42de545bb1024a39a2a8a09da50fcaace05bcd",
          "md5": "2298a4c49adf02ad0aa8d157a1d5b5b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-model-27.2.0-sources.jar",
          "url": "lint-model-27.2.0-sources.jar",
          "size": 44969,
          "sha512": "03724ae2f618310b79619bc6fc63169fa6ffd63f233aea36e3c82a8c10703c7a3888ed09459099d03cbd84fe43433df67bf6d30562e1ad444bcf2f278c493281",
          "sha256": "315b3ac9838f3f37f20a3d7798415ba82144361b1ae92cec3a56459a752ed587",
          "sha1": "ced9dedb23e2ecb5513b0d661f5d914b78b27695",
          "md5": "1407ad85553b8dfbe0b6bcb0b195ab28"
        }
      ]
    }
  ]
}
