{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.lint",
          "module": "lint-checks",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lint-27.2.0.jar",
          "url": "lint-27.2.0.jar",
          "size": 283546,
          "sha512": "470ffc3bc0201de824188cb0da32716b390a91af3ea01d3761e4bc5eb2d0214578bf7cb821e75199f6e5cf332295ab8b271388135d7b4729273cd437347c53b8",
          "sha256": "6722d1bff1eb89328c5d388a2dd89a84e5566ee813e918a72fb1dae750302b82",
          "sha1": "64122aa7325e56c1a3ddd155332e37513a0f9917",
          "md5": "e7d741c5f6d60e625b8957e9fd0a03ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.lint",
          "module": "lint-checks",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "lint-27.2.0.jar",
          "url": "lint-27.2.0.jar",
          "size": 283546,
          "sha512": "470ffc3bc0201de824188cb0da32716b390a91af3ea01d3761e4bc5eb2d0214578bf7cb821e75199f6e5cf332295ab8b271388135d7b4729273cd437347c53b8",
          "sha256": "6722d1bff1eb89328c5d388a2dd89a84e5566ee813e918a72fb1dae750302b82",
          "sha1": "64122aa7325e56c1a3ddd155332e37513a0f9917",
          "md5": "e7d741c5f6d60e625b8957e9fd0a03ba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-27.2.0-javadoc.jar",
          "url": "lint-27.2.0-javadoc.jar",
          "size": 46674,
          "sha512": "5b80e977f78ab57fde96ee5ef8216381472d67efebbeb307a34817f1c46ea3ae237d96888b41cdc3b38b067e8a157140d25c81237ded3a5e1218a69113a22595",
          "sha256": "11e326d43c98a7b2cb2b6ce2a1784eb1dd072c2b83d8ca2415594289800ca302",
          "sha1": "7ed0474f19bd8b48482a8f002be1bee24e8df59b",
          "md5": "ed5d2683f4ab5fb0083677a285369fc6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-27.2.0-sources.jar",
          "url": "lint-27.2.0-sources.jar",
          "size": 150890,
          "sha512": "b5df6fa3dd658c4a77d37f6c7daa5065da261fc4d408ae7aaeac9dff9b89e6b54cfec93d4cda144cc77a93f21e12a54fb0152c39d7c1ea68b530499a6b471e00",
          "sha256": "ccb73ea1aaebc38c6afeedb618a796a865df8af6fcc8c38720a7657e888c610e",
          "sha1": "c9fe70da7cf4d1a83e82b5d51af91246ba4fa9d7",
          "md5": "961667bddb064ea872654e56230a64ff"
        }
      ]
    }
  ]
}
