{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "sdklib",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "dvlib",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdklib-27.2.0.jar",
          "url": "sdklib-27.2.0.jar",
          "size": 637275,
          "sha512": "81051fb08019bc3432e482ac9ff2656d67ec4e3943bdd4db0654c699a102f6df056c7cdad2b785a9d7e4dd8a432a4e8b9be4b0dbf6fe5f36a59d05fdad9b6229",
          "sha256": "620b0d6f04751e8ec0dc0a72edab7458ba63297d4bd1c7e0d509575a6a3a2706",
          "sha1": "53d092eda5e71f3009209baa5f5ace3aaa5a7e33",
          "md5": "dab44e7cd137eba54f24c93e593ecb97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "dvlib",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.12"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdklib-27.2.0.jar",
          "url": "sdklib-27.2.0.jar",
          "size": 637275,
          "sha512": "81051fb08019bc3432e482ac9ff2656d67ec4e3943bdd4db0654c699a102f6df056c7cdad2b785a9d7e4dd8a432a4e8b9be4b0dbf6fe5f36a59d05fdad9b6229",
          "sha256": "620b0d6f04751e8ec0dc0a72edab7458ba63297d4bd1c7e0d509575a6a3a2706",
          "sha1": "53d092eda5e71f3009209baa5f5ace3aaa5a7e33",
          "md5": "dab44e7cd137eba54f24c93e593ecb97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdklib-27.2.0-javadoc.jar",
          "url": "sdklib-27.2.0-javadoc.jar",
          "size": 574276,
          "sha512": "596dcd7832fb4351fbeb7b9ef79c3345d9bc6aae114976fabfe83053237b4f958acebffa8fcbbcbca5f582d79ff2111c2bcf748cc8a811569e635b7173d84d24",
          "sha256": "09e305d7af6daa52c1be0b0cd43d63f2468f983ee369a6fcfb4f7747f1ea741b",
          "sha1": "b5a09e8adfb08651fcda2084314526e370c1e506",
          "md5": "9c5c7c11dda7db4ac26ae54b984694f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdklib-27.2.0-sources.jar",
          "url": "sdklib-27.2.0-sources.jar",
          "size": 1029802,
          "sha512": "a6f8684d601366da4d2f0550786e9c3d2d0ab6b9eb97b91ea05309d3f846865704fb4a7feff58245eb8d0be24cf330bfe11eaf205a553ae193245c2b4727195c",
          "sha256": "e94516d16aa3fbd6058b11f57d1dbc5dbe8b61aaf511eae154b8a017548f97af",
          "sha1": "063ccf8cf4ca4a067bf564b6392e2d0065f24aa0",
          "md5": "6622793a0aec24e3a7baf245178731be"
        }
      ]
    }
  ]
}
