{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "tracker",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "tracker-27.2.0.jar",
          "url": "tracker-27.2.0.jar",
          "size": 38725,
          "sha512": "ae0a5e09d526a503bc92f7d5050c2c17a1d14bdda81eaabdef46b6d7ddc8586ffc6a2d3cc7d952956dbecd9c35571102674febde2cd5d6d0f3907ab93c78f3b6",
          "sha256": "93b4c71c12336c21f14f38ce113cee37007d25c1b1a4fdcbf5cbe4bde873c8de",
          "sha1": "52946983ba7136bb94ba0e99eb7fbbe78a1a5b17",
          "md5": "7277ad92470650e734de0140e8a41ae4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "tracker-27.2.0.jar",
          "url": "tracker-27.2.0.jar",
          "size": 38725,
          "sha512": "ae0a5e09d526a503bc92f7d5050c2c17a1d14bdda81eaabdef46b6d7ddc8586ffc6a2d3cc7d952956dbecd9c35571102674febde2cd5d6d0f3907ab93c78f3b6",
          "sha256": "93b4c71c12336c21f14f38ce113cee37007d25c1b1a4fdcbf5cbe4bde873c8de",
          "sha1": "52946983ba7136bb94ba0e99eb7fbbe78a1a5b17",
          "md5": "7277ad92470650e734de0140e8a41ae4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracker-27.2.0-javadoc.jar",
          "url": "tracker-27.2.0-javadoc.jar",
          "size": 26075,
          "sha512": "d242db0ef9209b3bc43386bb397d7855c6002f70905121235ef7eeebfeb654fc532e5931fd63e5a6d8934b793e0b558bb9de17da60c012df20242f24f81be1c7",
          "sha256": "1a9038b674c6a29475cf0a03acdc0fcce6a82ffee7da2beefe046fdf2407fede",
          "sha1": "34347fb4859a7bcbb10cf62d12e91cf3f4bcb52a",
          "md5": "cb7466a4429d29073379d255cb01ef63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracker-27.2.0-sources.jar",
          "url": "tracker-27.2.0-sources.jar",
          "size": 18097,
          "sha512": "ffa410be6a2b7443010838b0d6ddfd4a7f4c90fd7da07b982455e3dfcae3c2fe802a9ee415b2c4e7ef987b3f7f85fb0bc572a6e46149c79ce59aaf9308504c2e",
          "sha256": "d24bb3ae8e7a8338c21002096494ea8dda7c1b4661f8d11fdb5c1d0464c7e228",
          "sha1": "c6d35bc4e5dcfe92d6afb7c97c342b8b7881319a",
          "md5": "b89c97f38f06344b5c1511b9a7fb9704"
        }
      ]
    }
  ]
}
