{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-gradle-api",
    "version": "27.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "lint-gradle-api-27.2.0.jar",
          "url": "lint-gradle-api-27.2.0.jar",
          "size": 18843,
          "sha512": "578ea7e14f85e9c061cc622d7622eb816d8c333253e316e4ec4ad4c6b32aa17ec3ca0ca5c511a8960350107b86481e869cfbedfecb7ab91f8045d9ae4a494034",
          "sha256": "44999582a56ea77667541ca9c25d4c5efaefb8d24353376218c634fc45c0c834",
          "sha1": "6ff70b4255a0458910d12f6c65017609618429a4",
          "md5": "f3418df2f6495617acc826703c1d5a9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "27.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "lint-gradle-api-27.2.0.jar",
          "url": "lint-gradle-api-27.2.0.jar",
          "size": 18843,
          "sha512": "578ea7e14f85e9c061cc622d7622eb816d8c333253e316e4ec4ad4c6b32aa17ec3ca0ca5c511a8960350107b86481e869cfbedfecb7ab91f8045d9ae4a494034",
          "sha256": "44999582a56ea77667541ca9c25d4c5efaefb8d24353376218c634fc45c0c834",
          "sha1": "6ff70b4255a0458910d12f6c65017609618429a4",
          "md5": "f3418df2f6495617acc826703c1d5a9d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-gradle-api-27.2.0-javadoc.jar",
          "url": "lint-gradle-api-27.2.0-javadoc.jar",
          "size": 18988,
          "sha512": "30f9a5d5fa583b02f1c91bd7a71567212f21d2a43aba1a768648b1048597a67d64fc4169f3b95d7a711555c43d964980a9ad8a4974378fd1777fcc1fdaee03ec",
          "sha256": "7be51993bf3b9cdee560a3da9d2262be44ebc35fdcb8aff8f8aa61dadfcaf70a",
          "sha1": "1e62fbee60c9761c28c300738092a14847f86eef",
          "md5": "6898101095390af3034594109e80f491"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-gradle-api-27.2.0-sources.jar",
          "url": "lint-gradle-api-27.2.0-sources.jar",
          "size": 14452,
          "sha512": "882c6cb01aa0b996d9a43cafc798c64910ec24c934d111155cea660d3fa5098c958b31f3355284ce31fcfa43b0c103f5a6a52923b29c9037511bdb13057c99f6",
          "sha256": "20affdb9d476a7f9dde9a0ab573839110791a7da61e38176bd6c05ab368fb17e",
          "sha1": "e7b983e72766afad7d8c8bff78496c9b7a759539",
          "md5": "17a21e76560e6b5855840a1bd5083c31"
        }
      ]
    }
  ]
}
