{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmgepvvbwbbsxntcttsqqniikq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-4.2.0.jar",
          "url": "builder-model-4.2.0.jar",
          "size": 100456,
          "sha512": "1a0e44fdc3836361267e08fdc343bfc13e9aa77e478c97a5a43d2a7d7d54c7c06c9f7b8535eaea346f0721f4fe04f59d0a1d1c19afe1471f806fd61aa2a675f2",
          "sha256": "9190614addae2e8dd8e759a329a648527859f92f7f55037446f5ea6962f4d670",
          "sha1": "5e5536e15c44135d0814be7a2ef64988207cab52",
          "md5": "cd5c00380f58c18172fa363005a15b12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "27.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-4.2.0.jar",
          "url": "builder-model-4.2.0.jar",
          "size": 100456,
          "sha512": "1a0e44fdc3836361267e08fdc343bfc13e9aa77e478c97a5a43d2a7d7d54c7c06c9f7b8535eaea346f0721f4fe04f59d0a1d1c19afe1471f806fd61aa2a675f2",
          "sha256": "9190614addae2e8dd8e759a329a648527859f92f7f55037446f5ea6962f4d670",
          "sha1": "5e5536e15c44135d0814be7a2ef64988207cab52",
          "md5": "cd5c00380f58c18172fa363005a15b12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-4.2.0-javadoc.jar",
          "url": "builder-model-4.2.0-javadoc.jar",
          "size": 230167,
          "sha512": "4608e26041d52c195ba21b40570d5e3a603890c5504db265c12c5666e4fdf0dfaa4901c52a00890bb5429bcd943382511c4ea9872cc8737189f302e3019b4693",
          "sha256": "a71c9971a3623b2b9705cc581fddc66949116f4e0faa810e7a5f52d7df137168",
          "sha1": "8b3868efbe5ff9cc86de84e0b385de60cd2ac982",
          "md5": "025233a647fc6248b2f20cf5a5a6f7ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-4.2.0-sources.jar",
          "url": "builder-model-4.2.0-sources.jar",
          "size": 129030,
          "sha512": "b1aa5c4736c089a41fa80ba66b39d77bf738a9cbc7a5766fdebf3d846c6fba89ecdd6815a19cfa4338c4bdab9080e8d27d8262d0ed9ee9bb8ffe4a98bcdfbac9",
          "sha256": "9ad603d56f0676849ef9b32189bd5ea1ba6dbd575f23dc25a467ed7c1c48a27e",
          "sha1": "c7bb17f57d01e33fdbda26e7963b0dc831e98700",
          "md5": "9e611fe1087ad1acca8afe7ea94e9d88"
        }
      ]
    }
  ]
}
