{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7178113"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.3.4.aar",
          "url": "navigation-common-ktx-2.3.4.aar",
          "size": 26400,
          "sha512": "1866829fc8999a60abb49ddbed41460b0f713961f17932c387dbee65d4ae10531c27f2a9b5fe538b723042ba4151445ca88dd01f5bba81b6c53a962a4c74b353",
          "sha256": "0f61606a89a1f6881696afc0f012b92a812a9f4e5861f4368f1060bb19c11d3f",
          "sha1": "7dd7996830cf81ff259381e723dbf8ff1c91471e",
          "md5": "56fa4abf35f4e85b0b2aa01cc8e1ff24"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.3.4.aar",
          "url": "navigation-common-ktx-2.3.4.aar",
          "size": 26400,
          "sha512": "1866829fc8999a60abb49ddbed41460b0f713961f17932c387dbee65d4ae10531c27f2a9b5fe538b723042ba4151445ca88dd01f5bba81b6c53a962a4c74b353",
          "sha256": "0f61606a89a1f6881696afc0f012b92a812a9f4e5861f4368f1060bb19c11d3f",
          "sha1": "7dd7996830cf81ff259381e723dbf8ff1c91471e",
          "md5": "56fa4abf35f4e85b0b2aa01cc8e1ff24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.3.4-sources.jar",
          "url": "navigation-common-ktx-2.3.4-sources.jar",
          "size": 9270,
          "sha512": "2e660b763af1be2ce6c7a11a357707f4b2661e1d087d7cd0f5b7d3ea35d274ed1e7be631eef53f23c25dac96233c22a2b88f801d44d276d15f50fe873cc9f0bb",
          "sha256": "3785b406ae010b5b2080a61ac30f34473414c7b49bd07f0c0ade32ab204c931a",
          "sha1": "1a3ce7c2b9dcc97c1d25ef6ab8e016b5a76de983",
          "md5": "7a3b42155cd6aca62a286819294a8545"
        }
      ]
    }
  ]
}
