{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7178113"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.4.aar",
          "url": "navigation-ui-ktx-2.3.4.aar",
          "size": 32272,
          "sha512": "94d4d4832ff97a07ec2d86603a83794bb779f6b70525b66e1d54076a229dc4c551bc755d665946a7a449547df1f9c945e0144397907a5626a00a3500aefaebf2",
          "sha256": "c39f933511d8149b69c0c82d4ea7219acecd3c0d103365640c02925025f8918f",
          "sha1": "680eb7aedfdf12b824c63efdf06ef4b7b28405c3",
          "md5": "53046ba1fcdc98f0e155273c19d1ef7c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.4.aar",
          "url": "navigation-ui-ktx-2.3.4.aar",
          "size": 32272,
          "sha512": "94d4d4832ff97a07ec2d86603a83794bb779f6b70525b66e1d54076a229dc4c551bc755d665946a7a449547df1f9c945e0144397907a5626a00a3500aefaebf2",
          "sha256": "c39f933511d8149b69c0c82d4ea7219acecd3c0d103365640c02925025f8918f",
          "sha1": "680eb7aedfdf12b824c63efdf06ef4b7b28405c3",
          "md5": "53046ba1fcdc98f0e155273c19d1ef7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.4-sources.jar",
          "url": "navigation-ui-ktx-2.3.4-sources.jar",
          "size": 8751,
          "sha512": "0d56d35c76ca24964807607764080077f0d8ce960dc61e14629a2a1d50bd424ab455be041d64dc17edc52511c0db4d25c3e7b359a5bb44c9c37f2e0934ea1685",
          "sha256": "dc293a071dc2f04f69d456de6734531fa52ae69fecc83a4e1812006a3e5e3eae",
          "sha1": "407dd936012d5b65b0af3e897ea62e436a811419",
          "md5": "e5ff0652316f70fa6f7263ce5094a7ba"
        }
      ]
    }
  ]
}
